
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import AdminProvider from "@/src/context/adminContext"; 
import { NotificationListener } from "@/src/components/NotificationListener"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LV Admin",
  description: "Generated by create next app",
};

function NotificationWrapper() {
  

  return (
    <NotificationListener
      userId={"admin11Sharafath"}
      role="admin"
    />
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AdminProvider>
          <NotificationWrapper /> 
          <ToastContainer />
          {children}
        </AdminProvider>
      </body>
    </html>
  );
}
