
export const TYPES = {
 
  MentorAuthController: Symbol.for('MentorAuthController'),
  MentorController: Symbol.for('MentorController'),
  AdminMentorController: Symbol.for('AdminMentorController'),
  AdminUserController: Symbol.for('AdminUserController'),
  AdminAuthController: Symbol.for('AdminAuthController'),
  AuthController: Symbol.for('AuthController'),
  ProfileController: Symbol.for('ProfileController'),
  UserController: Symbol.for("UserController"),  
  MentorProfileController: Symbol.for("MentroProfileController"),
  AdminCourseController: Symbol.for("AdminCourseController"),
  MentorStreamController: Symbol.for("MentorStreamController"),
  UserCourseController: Symbol.for("UserCourseController"),
  UserLiveCOntroller: Symbol.for("UserLiveController"),
  MentorLessonsController: Symbol.for("MentorLessonController"),
  UserLessonsController: Symbol.for("UserLessonsController"),
  MentorStudentsController: Symbol.for("MentorStudentsController"),
  mentorConcernController: Symbol.for("MentorConcernController"),
  UserDonationController: Symbol.for("UserDonationController"),
  AdminDonationCOntroller: Symbol.for("AdminDonationController"),
  NotificationController: Symbol.for("NotificationController"),
  MentorCommentController: Symbol.for("MentorCommentController"),
  UserCertificateController: Symbol.for("UserCertificateController"),
  SharedController: Symbol.for("SharedController"),
  MentorCourseController: Symbol.for("MentorCourseController"),
  AdminCategoryController: Symbol.for("AdminCategoryController"),
  AdminConcernController:Symbol.for("AdminConcernController"),
  
  // Services
  MentorAuthService: Symbol.for('MentorAuthService'),
  MentorService: Symbol.for('MentorService'),
  AdminMentorService: Symbol.for('AdminMentorService'),
  AdminUsersService: Symbol.for('AdminUsersService'),
  AdminAuthService: Symbol.for('AdminAuthService'),
  AuthService: Symbol.for('AuthService'),
  ProfileService: Symbol.for('ProfileService'),
  UserService: Symbol.for('UserService'),
  MentorProfileService: Symbol.for("MentorProfileService"),
  AdminCourseService: Symbol.for("AdminCourseService"),
  MentorStreamService: Symbol.for("MentorStreamServices"),
  UserCourseService: Symbol.for("UserCourseService"),
  UserLiveService: Symbol.for("UserLiveService"),
  MentorLessonsService: Symbol.for("MentorLessonService"),
  UserLessonsService: Symbol.for("UserLessonsService"),
  MentorStudentsService: Symbol.for("MentorStudentsService"),
  mentorConcernService: Symbol.for("MentorConcernService"),
  UserDonationServices: Symbol.for("UserDonationServices"),
  AdminDonationService: Symbol.for("AdminDonationService"),
  NotificationService: Symbol.for("NotificationService"),
  UserCertificateService:Symbol.for("UserCertificateService"),
  MentorCommentsService: Symbol.for("MentorCommentsService"),
  MentorCourseService: Symbol.for("MentorCourseService"),
  AdminCategoryService: Symbol.for("AdminCategoryService"),
  AdminConcernService:Symbol.for("AdminConcernService"),
  // Repositories
  MentorRepository: Symbol.for('MentorRepository'),
  MentorOtpRepository: Symbol.for('MentorOtpRepository'),
  AdminUsersRepository: Symbol.for('AdminUsersRepository'),
  UserRepository: Symbol.for('UserRepository'),
  OtpRepository: Symbol.for('OtpRepository'),
  AdminCourseRepository: Symbol.for("AdminCourseRepository"),
  AdminCategoriesRepository: Symbol.for("AdminCategoriesRepository"),
  MentorCourseRepository: Symbol.for("MentorCourseRepository"),
  CourseRepository: Symbol.for("CourseRepository"),
  LiveRepository: Symbol.for("LiveRespository"),
  SessionRepository: Symbol.for("SessionRepository"),
  LessonsRepository: Symbol.for("LessonRepository"),
  QuestionsRepository: Symbol.for("QuestionsRepository"),
  LessonReportRepository: Symbol.for("LessonReportRepository"),
  CommentsRepository: Symbol.for("CommentsRepository") ,
  CategoriesRepository: Symbol.for("CategoriesRepository"),
  ConcernRepository: Symbol.for("ConcernRepository"),
  DonationRepository: Symbol.for("DonationRepository"),
  UserCourseProgressRepository: Symbol.for("UserCourseProgressRepository"),
  NotificationRepository: Symbol.for("NotificationRepository"),
  UserLessonProgressRepository: Symbol.for("UserLessonProgressReposiory"),
  CertificateRepository: Symbol.for("CertificateRepository"),
  DailyTaskRepository: Symbol.for("DailyTaskRepository"),
  VoiceNoteRepository:Symbol.for("VoiceNoteRepository")
};