import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import { MentorsContextProvider, useMentorContext } from "@/src/context/mentorContext";
import HeaderWrapper from "@/src/components/mentor/HeaderWrapper";
import { NotificationListener } from "@/src/components/NotificationListener"; // ✅ import it

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "LV Mentor",
  description: "Generated by create next app",
};
function NotificationWrapper() {
  const { mentor } = useMentorContext();

  if (!mentor) return null;

  return (
    <NotificationListener
      userId={mentor._id || mentor.id}
      role="mentor"
    />
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MentorsContextProvider>
          <NotificationWrapper /> 
          <ToastContainer />
          <HeaderWrapper />
          {children}
        </MentorsContextProvider>
      </body>
    </html>
  );
}
