import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import { MentorsContextProvider } from "@/src/context/mentorContext";
import Header from "@/src/components/mentor/Header";
import HeaderWrapper from "@/src/components/mentor/HeaderWrapper";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LV Mentor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MentorsContextProvider>
          <ToastContainer />
          <HeaderWrapper />
        {children} 
        </MentorsContextProvider>
        
      </body>
    </html>
  );
}
